#pragma config(Motor,  port3,           RFWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LBWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LFWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBWheel,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1 == 1)
	{
			motor[RFWheel] = 50;
			motor[RBWheel] = 50;
			motor[LFWheel] = 50;
			motor[LBWheel] = 50;
  }
}
