#pragma config(Motor,  port3,           RWheel,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LWheel,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (1 == 1)
	{
		motor[RWheel] = vexRT(Ch2)*1;
		motor[LWheel] = vexRT(Ch3)*1;
		}

}
