#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Moving Forward
This program instructs your robot to move forward at full power for three seconds.
There is a two second pause at the beginning of the program.

Robot Model(s): Squarebot

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          VEX Motor             Right side motor
Motor Port 3        leftMotor           VEX Motor             Left side motor

*To run this sample program on Swervebot, be sure to Reverse Motor Port 3 in the Motors and Sensors
 Setup, and to make sure that Motor Port 2 is NOT Reversed.
----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	/*SEEMS TO SHIFT TO THE RIGHT
	while(1==1)
	{
		if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
		{
			motor[leftMotor] = 100;
			motor[rightMotor] = 40;
		}
		if(SensorValue[rightEncoder] < SensorValue[leftEncoder])
			{
				motor[leftMotor] = 40;
				motor[rightMotor] = 40*abs(cosDegrees(SensorValue[rightEncoder]-SensorValue[leftEncoder]));
			}
		else if(SensorValue[leftEncoder] < SensorValue[rightEncoder])
			{
				motor[leftMotor] = 40*abs(cosDegrees(SensorValue[rightEncoder]-SensorValue[leftEncoder]));
				motor[rightMotor] = 40;
			}
	}
	*/

	// THIS IS THE CODE THAT WORKS
	while(1==1)
	{
		if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
		{
			motor[leftMotor] = 50;
			motor[rightMotor] = 50;
		}
		else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
			{
				motor[leftMotor] = 50;
				motor[rightMotor] = 30;
		//	int difference = SensorValue[rightEncoder] - SensorValue[leftEncoder]; //Degreees
		//	motor[leftMotor] += difference;
			}
		else if(SensorValue[leftEncoder] > SensorValue[rightEncoder])
			{
				motor[leftMotor] = 30;
				motor[rightMotor] = 50;
			}
		}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

/*

in1 	= left line follower
in2 	= center line follower
in3 	= right line follower
in4 	= gyro
in6 	= arm potentiometer
dgtl1	= right encoder
dgtl3 = left encoder
dgtl6 = touch
dgtl8 = sonar (cm)

*/
