#pragma config(Motor,  port2,           FLWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FRWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BLWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BRWheel,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

		whil
		e (true)
		{
			motor(BRWheel) = vexRT[Ch2];
			motor(FRWheel) = vexRT[Ch2];
			motor(BLWheel) = vexRT[Ch3];
			motor(FLWheel) = vexRT[Ch3];
			}
}
