#pragma config(Motor,  port1,           FRWheel,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           FLWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BRWheel,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           BLWheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1 == 1)
	{
	motor[FRWheel] = vexRT(Ch2)*.98;
	motor[FLWheel] = vexRT(Ch2)*.98;
	motor[BRWheel] = vexRT(Ch3)*.98;
	motor[BLWheel] = vexRT(Ch3)*.98;
	}
}
