#pragma config(Motor,  port4,           RWheel,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           LWheel,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1 == 1)
	{
	motor[RWheel] = vexRT(Ch2)*.98;
	motor[LWheel] = vexRT(Ch3)*-.98;
	}
}
