#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int test = 0;
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;

	float diameterOfWheel = 4.25; //inches
  float circumference = diameterOfWheel*PI;

  int distanceToGo = 12; //inches

  float rotations = distanceToGo/circumference;
  float degreesToTurn = rotations*360; //Degrees to turn to go distance.
	while(1==1)
	{
		motor[leftMotor] = 50;
		motor[rightMotor] = 50;
		test+=1;
		if(SensorValue[rightEncoder] > SensorValue[leftEncoder]){
			int difference = SensorValue[rightEncoder] - SensorValue[leftEncoder]; //Degreees
			motor[leftMotor] += difference;
		}
		else if(SensorValue[leftEncoder] > SensorValue[rightEncoder]){
			int difference = SensorValue[leftEncoder] - SensorValue[rightEncoder];
			motor[rightMotor] += difference;
		}
	}

}
