#pragma config(Sensor, dgtl7,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl10, rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;

	while(1==1)
	{
		motor[leftEncoder] = 90;
		motor[rightMotor] = 90;
	}
}

//Change the name of the port to test if it works.
