#pragma config(Motor,  port2,           clawGrip,      tmotorVex393_MC29, openLoop)           //2 Opens and Closes
#pragma config(Motor,  port3,           RFWheel,       tmotorVex393_MC29, openLoop, reversed) //3 Right Front Wheel
#pragma config(Motor,  port4,           LBWheel,       tmotorVex393_MC29, openLoop)           //4 Left Back Wheel
#pragma config(Motor,  port5,           LFWheel,       tmotorVex393_MC29, openLoop, reversed) //5 Left Front Wheel
#pragma config(Motor,  port6,           RBWheel,       tmotorVex393_MC29, openLoop)           //6 Right Back Wheel
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
 
task main()
{
	while (1 == 1)
	{
		//Joystick #1: Movement and Lift(ports 2, 3, 4, 5, 6, 9)

		motor[RFWheel] = vexRT(Ch2)*-1;
		motor[RBWheel] = vexRT(Ch2)*-1;

		motor[LFWheel] = vexRT(Ch3)*1;
		motor[LBWheel] = vexRT(Ch3)*1;
	}
}
